# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:
  engine: bing # google/baidu/bing
  url: /search

# friends link
links:
  - name: cnblog
    url: https://cnblogs.com/oldhelps
  - name: OLDHELPS English Blog
    url: https://ohen.hashnode.dev/
  - name: Gitee
    url: https://gitee.com/oldhelps
  - name: Bilibili
    url: https://space.bilibili.com/3461578863151729

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: Categories
    slug: categories
    url: /categories
  - name: Tags
    slug: tags
    url: /tags
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud


# use url, not username
social:
- slug: github
  url: https://github.com/oldhelps
# - slug: twitter
#   url: https://twitter.com/your_twitter_username
- slug: rss
	url: /atom.xml


# title image
title_image: /img/title.jpg
