# Search
search: 
  enable: true
  service: bing # baidu, google, bing, so, yahoo, duckduckgo, sougou

# friends link
links:
  - name: cnblog
    url: https://cnblogs.com/oldhelps
  - name: OLDHELPS English Blog
    url: https://ohen.hashnode.dev/
  - name: Gitee
    url: https://gitee.com/oldhelps
  - name: Bilibili
    url: https://space.bilibili.com/3461578863151729

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: Categories
    slug: categories
    url: /categories
  - name: Tags
    slug: tags
    url: /tags
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud


# use url, not username
social:
- slug: github
  url: https://github.com/oldhelps
# - slug: twitter
#   url: https://twitter.com/your_twitter_username
- slug: rss
	url: /atom.xml


# title image
title_image: https://s2.loli.net/2025/08/09/RMeXpfw2sScFuUO.jpg

hero_image: 2.png
hero_title: 老帮帮的博客
hero_subtitle: 老帮帮的博客。

author:
  name: 老帮帮
  bio : Tempora mutantur, nos et mutamur in illis ...djkadj

comments:
  enable: false
  code: 	 # your <script> tag

seo: #meta tags for SEO
  description: 老帮帮的博客
  keywords: [老帮帮, 博客, 技术, 分享]
  author: 老帮帮


clarity: # Microsoft Clarity
  enable: false
  code: '' # your clarity code

busuanzi: # 文章阅读量统计
  enable: true
